services:
  db:
    image: postgres:16
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app_net

  patient_service:
    build:
      context: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SERVICE_NAME="PATIENT-SERVICE"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "6543:6543"
    networks:
      - app_net

  user_service:
    build:
      context: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - SERVICE_NAME="USER-SERVICE"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "6544:6543"
    networks:
      - app_net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - patient_service
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net: